### ISSUE TITLE
Mettre à jour la documentation de l'API-BAL

### ISSUE THREAD

**Issue by GllmR** [BaseAdresseNationale/mes-adresses-api#298]
L'API-BAL a été mise à jour plusieurs fois pour intégrer des fonctionnalités liées à mes-adresses ou pour ajouter des routes.

Sa documentation fait l'impasse sur les dernières nouveautés ajoutées, il faut donc la mettre à jour.

**Comment by tmerlier** [comment]
La documentation a été [mise à jour](https://github.com/BaseAdresseNationale/mes-adresses-api/wiki/Documentation-de-l'API/14e851045cd0b25d1daa0ec931483124db79fb30)
