### ISSUE TITLE
Utilisation de la fonction count() dépréciée

### ISSUE THREAD

**Issue by jdesboeufs** [BaseAdresseNationale/mes-adresses-api#333]
La fonction `count()` est utilisée à plusieurs reprises dans le code.
Cette fonction est désormais dépréciée de la bibliothèque `mongodb` que nous utilisons et sera supprimée lors d'une future version majeure.

Il faut remplacer par `countDocuments()` ou par `estimatedDocumentCount()` en fonction des cas de figure.

**Comment by jdesboeufs** [comment]
Références :
https://www.mongodb.com/docs/drivers/node/current/usage-examples/count/
https://mongodb.github.io/node-mongodb-native/4.5/classes/Collection.html#count

**Comment by vinsag** [comment]
L'issue a été résolue ce jour
