### ISSUE TITLE
Supprimer les espaces superflus pour les langues régionales

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/mes-adresses-api#348]
## Contexte
Les alternatives régionales ne sont actuellement pas traitées, ce qui veut dire que si par exemple des espaces se trouve en début ou en fin de chaine, alors, ils ne sont pas retirés.

## Évolutions
Appliquer le traitement `cleanNom` à toutes les alternatives régionales des voies et des toponymes, comme c'est le cas pour le moment pour les noms de voie.

**Comment by jdesboeufs** [comment]
Faudrait trouver un meilleur titre à cette issue car c'est cryptique x)
