### ISSUE TITLE
L'endpoint /search ne renvoie pas systématiquement le nom d'une commune

### ISSUE THREAD

**Issue by qloridant** [BaseAdresseNationale/mes-adresses-api#398]
# Contexte

En souhaitant que l'API renvoie le nom d'une commune quand on envoie le code INSEE de cette commune, j'ai essayé cette requête
`https://api-adresse.data.gouv.fr/search/?q=${inseeCode}&type=municipality&citycode=${inseeCode}` 

# Problème
Cette requête renvoie bien la commune la plupart du temps, ex : `https://api-adresse.data.gouv.fr/search/?q=75115&type=municipality&citycode=75115`  renvoie bien l'objet ville de Paris.

Par contre dans le cas du code Insee 13208, code du 8ème arrondissement de Marseille, la requête `https://api-adresse.data.gouv.fr/search/?q=13208&type=municipality&citycode=13208` ne nous renvoie pas l'objet ville de Marseille alors que c'est le comportement auquel je m'attend.

# Solution
* Existe-t-il un meilleur moyen d'accéder au nom de la commune depuis le code INSEE ?
* [Un filtre](https://public.opendatasoft.com/explore/dataset/correspondance-code-insee-code-postal/table/?flg=fr&q=13208) m'a montré que ce code particulier (13208) apparaît dans un champ idGeoFla pour une autre commune. Peut-être que ce duplicat peut expliquer le comportement ?

**Comment by fufeck** [comment]
Bonjour,

L'url https://api-adresse.data.gouv.fr ne pointe pas sur mes-adresse-api, vous pouvez trouver le nom de votre commune directement avec https://github.com/etalab/decoupage-administratif
